# Generated by Django 6.0.4 on 2026-05-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options_remove_job_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
