# Generated by Django 6.0.4 on 2026-05-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, help_text='Ex: 6 LPA', max_length=50, null=True),
        ),
    ]
